# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left Right Block"
  description:
  icon: nature_people
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  flip: false
  title: "Hello World!"
  tagline: "Hello World!"
  image: "https://placekitten.com/1000/500"
  image_alt: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
