# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Burger"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  components:
    - bookshop:structure:burger!(burger/top-bun)
    - bookshop:structure:burger!(burger/patty)
    - bookshop:structure:burger!(burger/bottom-bun)

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
